### ISSUE TITLE
DamageText가 표기되지  않는 버그

### ISSUE THREAD

**Issue by Barone12** [Duet-Forte/Duet-Forte#31]
![image](https://github.com/Duet-Forte/Duet-Forte/assets/100332233/63ab561e-f3c8-489a-8db4-e46b588d6798)

Scene에서는 보이는데 

![image](https://github.com/Duet-Forte/Duet-Forte/assets/100332233/a53c796e-a83c-43c2-91fd-d4ba490913df)

Game에서는 안보임...

**Comment by wave-sound** [comment]
게임에 등장하는 대부분의 UI를 카메라 기반으로 변경했기에 발생한 오류. (DOTween 관련) 스킬창과 적 정보 뜨는 건 수정했는데, 데비지 텍스트 수정을 깜빡함. 근시일내에 수정하겠습니다

**Comment by Barone12** [comment]
인지했고 공부할겸 건드려봐서 보이는 거까지 다 구현해놨는데 dotween이 작동 안됨
